service: contact-service
useDotenv: true
provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  #timeout: 120
  environment:
    MONGO_URI: ${env:MONGO_URI}
    BUCKET_NAME: ${env:BUCKET_NAME}
    EVENT_BUS_NAME: default
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*
        
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:ap-south-1:${aws:accountId}:event-bus/default

  httpApi:
    authorizers:      
      jwtAuthorizer:
        type: jwt
        identitySource: 
          - $request.header.Authorization
        issuerUrl: https://cognito-idp.ap-south-1.amazonaws.com/ap-south-1_Y0tHEPU6x
        audience:
          - 7h9mutph8gclo7uoeeloepa3oo

plugins:
  - serverless-offline

resources:
  Resources:
    ImageDeleteQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-image-delete-queue

    ImageDeleteRule:
      Type: AWS::Events::Rule
      Properties:
        EventPattern:
          source:
            - contact-service
          detail-type:
            - ContactImageDeleted
        Targets:
          - Arn: !GetAtt ImageDeleteQueue.Arn
            Id: ImageDeleteQueueTarget

    ImageDeleteQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - !Ref ImageDeleteQueue
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: events.amazonaws.com
              Action: sqs:SendMessage
              Resource: !GetAtt ImageDeleteQueue.Arn

functions:
  createContact:
    handler: src/handlers/createContact.handler
    events:
      - httpApi:
          path: /contacts
          method: post
          authorizer:
            name: jwtAuthorizer

  getContacts:
    handler: src/handlers/getContacts.handler
    events:
      - httpApi:
          path: /contacts
          method: get
          authorizer:
            name: jwtAuthorizer

  generateUploadUrls:
    handler: src/handlers/generateUploadUrls.handler
    events:
      - httpApi:
          path: /uploads/presigned-urls
          method: post
          authorizer:
            name: jwtAuthorizer

  getViewUrl:
    handler: src/handlers/getViewUrls.handler
    events:
      - httpApi:
          path: /uploads/view-url
          method: get
          authorizer:
            name: jwtAuthorizer

  updateContact:
    handler: src/handlers/updateContact.handler
    events:
      - httpApi:
          path: /contacts/{id}
          method: put
          authorizer:
            name: jwtAuthorizer

  deleteImages:
    handler: src/handlers/deleteImages.handler
    events:
      - sqs:
          arn: !GetAtt ImageDeleteQueue.Arn